#!/usr/bin/env bash

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "SSHの鍵が存在しなかったら作成します..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "パーミッションを修正します..."
  successfully sudo mkdir -p /usr/local
  successfully sudo chown -R `whoami` /usr/local

echo "Homebrewをインストールします..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "HomebrewがインストールされたディレクトリをPATHに追加します..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.bashrc
  successfully source ~/.bashrc

echo "GCCなどをインストールします..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Rubyをインストールするのに必要なパッケージをインストールします..."
  successfully brew install gdbm libffi libksba libyaml

echo "MySQLをインストールします..."
  successfully brew install mysql

echo "Redisをインストールします..."
  successfully brew install redis

echo "ImageMagickをインストールします..."
  successfully brew install imagemagick

echo "Qtをインストールします..."
  successfully brew install qt

echo "RVMをインストールします..."
  successfully curl -L https://get.rvm.io | bash -s stable

echo "Ruby 1.9.2-p318をインストールします..."
  successfully rvm install 1.9.2-p318 --default

echo "Ruby 1.9.3-p125をインストールします..."
  successfully rvm install 1.9.3-p125

echo "シェルを再起動します..."
  exec $SHELL -l
